pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat script: '''
                     gradlew build


       
       
                ''',
            label: "Building Project"
           }
            }
        stage('Test')
        {
            steps {
                bat script: '''
                    echo "I am in Test step"

                    gradlew test
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                bat script: '''
                    echo "I am in Sonarqube scan"
                ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                bat script: '''
                    docker build . -t "firstrepo"
                ''',
            label: "Building Docker Image"
            }
        }
        stage('Publish DockerImage')
        {
            steps {
                bat script: '''
                   docker login -u=rajattavisca27 -p=Rajjothehero@12
                    docker push rajattavisca27/firstrepo:firstrepo
                    ''',
            label: "Publishing Docker Image"
            }
        }
    }
  }
